# Generated by Django 4.1.6 on 2023-02-09 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("first", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="department",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employeeId",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="employee_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="econtact",
            field=models.CharField(default=django.utils.timezone.now, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="eemail",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="eid",
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="ename",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="employee",
            name="id",
            field=models.AutoField(
                auto_created=True,
                default=django.utils.timezone.now,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="employee",
            table="employee",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
